[package]
name = "rust-testing-explored"
version = "0.1.0"
edition = "2021"

[dependencies]
openapi-schema = "0.1.10"

[dev-dependencies]
insta = { version = "1.39.0", features = ["json"] }
rstest = "0.19.0"
