[toolchain]
# Need `nightly` for fuzzing. Picked a random slightly older version as many more recent
# ones weren't available, and I ran into
# https://github.com/rust-lang/rust-analyzer/issues/16331 .
channel = "nightly-2023-10-20"
